config/routes.rb
Rails.application.routes.draw do
  # show our todo index page for as root page
  root 'todos#index'

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

    # GET /todos
    # GET /todos.json
    def index
        @todo = Todo.new
        # also order the todo's
        @todos = Todo.order(:id)
    end

    # GET /todos/1
    # GET /todos/1.json
    def show
    end

    # GET /todos/new
    def new
        @todo = Todo.new
    end

    # GET /todos/1/edit
    def edit
    end

    # POST /todos
    # POST /todos.json
    def create
        @todo = Todo.new(todo_params)
        respond_to do |format|
            if @todo.save
                format.html { redirect_to todos_path, notice: 'Todo was successfully created.' }
                format.json { render :show, status: :created, location: @todo }
            else
                format.html { render :new }
                format.json { render json: @todo.errors, status: :unprocessable_entity }
              end
        end
    end

    # PATCH/PUT /todos/1
    # PATCH/PUT /todos/1.json
    def update
        respond_to do |format|
            if @todo.update(todo_params)
                format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
                format.json { render :show, status: :ok, location: @todo }
            else
                format.html { render :edit }
                format.json { render json: @todo.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /todos/1
    # DELETE /todos/1.json
    def destroy
        @todo.destroy
        respond_to do |format|
            format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_todo
        @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
        params.require(:todo).permit(:title, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoAjax</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
    <%= yield %>
  </div>
  
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_for(todo) do |f| %>
  <div class="form-group <%= todo.errors.any? ? 'has_error' : '' %>">
    <%= f.text_field :title, placeholder: "What needs to be done?", class: 'form-control' %>
    <% if todo.errors.any? %>
      <% todo.errors.full_messages.each do |message| %>
        <span class="help-block"><%= message %></span>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<tr class="todo <%= todo.completed? ? "success" : "" %>" data-id="<%= todo.id %>">
  <td>
    <input name="todo[<%= todo.id %>]" id="todo-<%= todo.id %>" type="checkbox" value="1" <%= todo.completed? ? 'checked="checked"' : '' %>>
  </td>
  <td>
    <label for="todo-<%= todo.id %>"><%= todo.title %></label>
  </td>
</tr>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="page-header">TodoList</h1>

        <% if notice.present? %>
        <div class="alert alert-info" role="alert">
            <%= notice %>
        </div>
        <% end %>

        <%= render "form", todo: @todo %>

        <hr/>

        <table class="table table-striped">
            <%= render @todos %>
        </table>

        <div class="footer">
            Todo:
            <span id="todo-count">1</span>
            • Done:
            <span id="completed-count">0</span>
            • Total:
            <span id="total-count">1</span>
            •
            <a href="#" id="clean-up">Clean up</a>
        </div>
    </div>

</div>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo.completed %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>